site_name: Kingdom Keys Re:Coded Docs
pages:
- Home: 'index.md'
- Blocks:
    - 'Blast Blox': 'blocks/blastblox.md'
    - 'Bounce Blox': 'blocks/bounceblox.md'
    - 'Chest': 'blocks/chest.md'
    - 'Danger Blox': 'blocks/dangerblox.md'
    - 'Ghost Blox': 'blocks/ghostblox.md'
    - 'Hard Blox': 'blocks/hardblox.md'
    - 'Magnet Blox': 'blocks/magnetblox.md'
    - 'Metal Blox': 'blocks/metalblox.md'
    - 'Normal Blox': 'blocks/normalblox.md'
    - 'Prize Blox': 'blocks/prizeblox.md'
    - 'Rare Prize Blox': 'blocks/rareprizeblox.md'
    - 'Synthesis Ores': 'blocks/synthesisores.md'
    - 'Synthesis Table': 'blocks/synthesistable.md'
- Items:
    - 'Recipe': 'items/recipe.md'
    - 'Synthesis Materials': 'items/synthesismaterials.md'
    - 'Synthesis Bags': 'items/synthesisbags.md'
- Keyblades:
    - 'About Keyblades': 'keyblades/keyblades.md'
    - 'Kingdom Key': 'keyblades/kingdomkey.md'
- Keychains:
    - 'About': 'keychains/about.md'
    - 'Kingdom Key Chain': 'keychains/kingdomkeychain.md'
theme: readthedocs